### ISSUE TITLE
More automated process for astropy release

### ISSUE THREAD

**Issue by pllim** [astropy/astropy-project#97]
As a prerequisite for #95 .

See https://github.com/astropy/project/issues/95#issuecomment-629236501 by @astrofrog .

**Comment by pllim** [comment]
Here is an example to auto-push a release to PyPI using GitHub Actions:

https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

<details>
  <summary>Click to see example YAML</summary>

```yaml
name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist bdist_wheel
        twine upload dist/*
```

</details>
